default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test
